stdmanage/urls.py
from django.urls import path 
from .views import *

app_name = 'stdmanage'
urlpatterns = [
    path('', IndexView.as_view(), name = 'index'),

    path('readingclass-create/', ReadingClassCreateView.as_view(), name = 'readingclass-create'),
    path('readingclass-update/<int:pk>/', ReadingClassUpdateView.as_view(), name = 'readingclass-update'),
    path('readingclass-delete/<int:pk>/', ReadingClassDeleteView.as_view(), name = 'readingclass-delete'),
    path('readingclass-list/<int:page_no>', ReadingClassListView.as_view(), name = 'readingclass-list'),
    
    path('student-create/', StudentCreateView.as_view(), name = 'student-create'),
    path('student-update/<int:pk>/', StudentUpdateView.as_view(), name = 'student-update'),
    path('student-delete/<int:pk>/', StudentDeleteView.as_view(), name = 'student-delete'),
    path('student-detail/<int:pk>/', StudentDetailView.as_view(), name = 'student-detail'),
    path('student-list/<int:page_no>/', StudentListView.as_view(), name = 'student-list'),
    
    path('exam-create/', ExamCreateView.as_view(), name='exam-create'),
    path('exam-update/<int:pk>/', ExamUpdateView.as_view(), name='exam-update'),
    path('exam-delete/<int:pk>/', ExamDeleteView.as_view(), name='exam-delete'),
    path('exam-detail/<int:pk>/', ExamDetailView.as_view(), name='exam-detail'),
    path('exam-list/<int:page_no>/', ExamListView.as_view(), name='exam-list'),

    path('subject-create/', SubjectCreateView.as_view(), name = 'subject-create'),
    path('subject-update/<int:pk>/', SubjectUpdateView.as_view(), name = 'subject-update'),
    path('subject-delete/<int:pk>/', SubjectDeleteView.as_view(), name = 'subject-delete'),
    path('subject-list/<int:page_no>', SubjectListView.as_view(), name = 'subject-list'),
    
    path('result-create/', ResultCreateView.as_view(), name='result-create-basic'),
    path('result-create/<str:exam>/<str:subject>/<int:student>', ResultCreateView.as_view(), name='result-create'),
    path('result-update/<int:pk>/', ResultUpdateView.as_view(), name='result-update'),
    path('result-delete/<int:pk>/', ResultDeleteView.as_view(), name='result-delete'),
    path('result-add-list/<int:page_no>/', ResultAddListView.as_view(), name='result-add-list'),
    path('result-list/<int:page_no>/', ResultListView.as_view(), name='result-list'),

    
]

student/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('stdmanage.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stdmanage/models.py
from django.db import models
from django.urls import reverse


class ReadingClass(models.Model):

    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("stdmanage:readingclass-list", kwargs={"page_no": 1})


class Student(models.Model):
      
    GENDER = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('others', 'Others')
    ]
    full_name = models.CharField(
        max_length=60
        )
    gender = models.CharField(
        max_length=10, 
        default='male', 
        choices=GENDER
        )
    date_of_birth = models.DateField(
        null=True, 
        blank=True, 
        )
    reading_class = models.ForeignKey(
        ReadingClass, 
        on_delete=models.CASCADE
        )
    phone_number = models.CharField(
        max_length=20
        )
    home_address = models.CharField(
        max_length=200, 
        null= True, 
        blank=True, 
        )
    photo = models.FileField(
        upload_to='student_photos', 
        null=True
        )

    def get_absolute_url(self):
        return reverse('stdmanage:student-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.full_name


class Exam(models.Model):
    
    name = models.CharField(
        max_length=50
        )
    description = models.CharField(
        max_length=200
        )
    date = models.DateField()
    question_papers = models.FileField(
        upload_to='question_papers',  
        )
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("stdmanage:exam-detail", kwargs={"pk": self.pk})


class Subject(models.Model):

    name = models.CharField(
        max_length=20
        )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("stdmanage:subject-list", kwargs={"page_no": 1})


class Result(models.Model):

    score = models.CharField(
        max_length=10
        )
    answer_sheet = models.FileField(
        upload_to='answer_sheets'
        )
    student = models.ForeignKey(
        Student, 
        on_delete=models.CASCADE
        )
    subject = models.ForeignKey(
        Subject, 
        on_delete=models.CASCADE
        )
    exam = models.ForeignKey(
        Exam, 
        on_delete=models.CASCADE
        )
    
    def __str__(self):
        return self.student.full_name + "'s score"

    def get_absolute_url(self):
        return reverse("stdmanage:result-list", kwargs={"page_no": 1})

stdmanage/forms.py
from django import forms

from .models import *


class StudentForm(forms.ModelForm):
    
    class Meta:
        model = Student
        fields = '__all__'
        YEARS = {
            '1999':'1999',
            '2001':'2001',
            '2002':'2002',
            '2003':'2003',
            '2004':'2004',
            '2005':'2005',
            '2006':'2006',
            '2007':'2007',
            '2008':'2008',
            '2009':'2009',
            '2010':'2010',
        }
        widgets = {
            'date_of_birth': forms.DateInput( attrs={'type': 'date',} ),
            'home_address': forms.Textarea( attrs={'cols': '20', 'rows': '5'} ),
        }
        labels = {
            'full_name': 'Enter full name of the student',
        }
        help_texts = {

        }
        error_messages = {

        }


class ExamForm(forms.ModelForm):
    
    class Meta:
        model = Exam
        fields = '__all__'
        widgets = {
            'date': forms.SelectDateWidget,
            'description': forms.Textarea(attrs={'rows': '5'})
        }


class ResultForm(forms.ModelForm):

    class Meta:
        model = Result
        fields = '__all__'


class ReadingClassForm(forms.ModelForm):

    class Meta:
        model = ReadingClass
        fields = '__all__'
   

class SubjectForm(forms.ModelForm):

    class Meta:
        model = Subject
        fields = '__all__'
   

stdmanage/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic

from .models import *
from .forms import *


class IndexView(generic.View):
    template_name = 'stdmanage/index.html'

    def get(self,request, *args, **kwargs):
        context = {}
        context["student_count"] = Student.objects.all().count()
        context["recent_students"] = Student.objects.all()[:5]
        context["recent_exams"] = Exam.objects.all()[:3]
        context["recent_result"] = Result.objects.all()[:5]

        return render(request, self.template_name, context)



class StudentCreateView(generic.CreateView):
    template_name = 'stdmanage/form.html'
    form_class = StudentForm
    model = Student
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create Student Record'
        context['submit_text'] = 'Create Student'
        return context


class StudentUpdateView(generic.UpdateView):
    template_name = 'stdmanage/form.html'
    form_class = StudentForm 
    model = Student
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Student Record'
        context['submit_text'] = 'Update Student'
        return context


class StudentDeleteView(generic.DeleteView):
    model = Student
    success_url = reverse_lazy('stdmanage:student-list', kwargs={'page_no': 1})
    template_name = 'stdmanage/confirm_delete.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        the_object = self.model.objects.get(id = self.kwargs['pk'])
        title = "Are you sure you want to delete student " + the_object.full_name + " ?" 
        context['title'] = title
        context['delete_url_name'] = 'stdmanage:student-delete'
        context['go_back_url'] = reverse('stdmanage:student-detail', kwargs={'pk': the_object.id})
        return context


class StudentListView(generic.View):
    template_name = "stdmanage/student_list.html"
    
    def get_list(self,request, *args, **kwargs):
        context = {}
        
        context['all_class'] = ReadingClass.objects.all()
        
        try:
            context["reading_class"] = request.session["reading_class"]
        except:
            context["reading_class"] = "all"
            request.session["reading_class"] = "all"
        
        if context["reading_class"] != "all":
            reading_class = ReadingClass.objects.get(name = request.session["reading_class"])
            student_list = Student.objects.filter(reading_class = reading_class)
        else:
            student_list = Student.objects.all()
        
        return [context, student_list]

    def get(self, request, *args, **kwargs):
        res = self.get_list(request, *args, **kwargs)
        context = res[0]
        list_object = res[1]

        try:
            page_size = int(request.session["page_size"])
        except:
            page_size = 5
            request.session["page_size"] = page_size
        context["page_size"] = page_size

        try:
            page_no = kwargs["page_no"]
        except:
            page_no = 1

        context["list_object"] = list_object[ ( page_no - 1 ) * page_size : page_no * page_size ]
        
        count = len(list_object)
        i = 1
        pages = []
        while count >= 0:
            pages.append(i)
            i += 1
            count -= page_size

        context["pages"] = pages
        context["current"] = page_no

        if page_no != pages[0]:
            context["prev"] = page_no - 1
        else:
            context["prev"] = 1

        if page_no != pages[-1]:
            context["next"] = page_no + 1
        else:
            context["next"] = pages[-1]

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        try:
            request.session["reading_class"] = request.POST["reading_class"]
        except:
            pass
        try:
            request.session["page_size"] = request.POST["page_size"]
        except:
            pass
        
        return HttpResponseRedirect(reverse("stdmanage:student-list", kwargs={
            "page_no": 1
        }))


class StudentDetailView(generic.DetailView):
    model = Student
    context_object_name = 'student_detail'


class ReadingClassCreateView(generic.CreateView):
    template_name = 'stdmanage/form.html'
    model = ReadingClass
    form_class = ReadingClassForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create New Reading Class'
        context['submit_text'] = 'Create'
        return context


class ReadingClassUpdateView(generic.UpdateView):
    template_name = 'stdmanage/form.html'
    model = ReadingClass
    form_class = ReadingClassForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Reading Class'
        context['submit_text'] = 'Update'
        return context


class ReadingClassDeleteView(generic.DeleteView):
    model = ReadingClass
    success_url = reverse_lazy("stdmanage:readingclass-list", kwargs = {"page_no": 1})
    template_name = 'stdmanage/confirm_delete.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        the_object = self.model.objects.get(id = self.kwargs['pk'])
        title = "Are you sure you want to delete class " + the_object.name + " ?" 
        context['title'] = title
        context['delete_url_name'] = 'stdmanage:readingclass-delete'
        context['go_back_url'] = reverse('stdmanage:readingclass-list', kwargs={"page_no": 1})
        return context


class ReadingClassListView(StudentListView):
    template_name = 'stdmanage/readingclass_list.html'
    
    def get_list(self, request, *args, **kwargs):
        context = {}
        all_class = ReadingClass.objects.all()
        return context, all_class
    
    def post(self, request, *args, **kwargs):
        try:
            request.session["page_size"] = request.POST["page_size"]
        except:
            pass
        
        return HttpResponseRedirect(reverse("stdmanage:readingclass-list", kwargs={
            "page_no": 1
        }))


class SubjectCreateView(generic.CreateView):
    template_name = 'stdmanage/form.html'
    model = Subject
    form_class = SubjectForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create New Teaching Subject'
        context['submit_text'] = 'Create'
        return context


class SubjectUpdateView(generic.UpdateView):
    template_name = 'stdmanage/form.html'
    model = Subject
    form_class = SubjectForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Subject'
        context['submit_text'] = 'Update'
        return context


class SubjectDeleteView(generic.DeleteView):
    model = Subject
    success_url = reverse_lazy("stdmanage:subject-list", kwargs={'page_no': 1})
    template_name = 'stdmanage/confirm_delete.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        the_object = self.model.objects.get(id = self.kwargs['pk'])
        title = "Are you sure you want to delete subject " + the_object.name + " ?" 
        context['title'] = title
        context['delete_url_name'] = 'stdmanage:subject-delete'
        context['go_back_url'] = reverse('stdmanage:subject-list', kwargs={"page_no": 1})
        return context


class SubjectListView(StudentListView):
    template_name = 'stdmanage/subject_list.html'
    
    def get_list(self, request, *args, **kwargs):
        context = {}    
        all_subjects = Subject.objects.all()
        return context, all_subjects
    
    def post(self, request, *args, **kwargs):
        try:
            request.session["page_size"] = request.POST["page_size"]
        except:
            pass
        
        return HttpResponseRedirect(reverse("stdmanage:subject-list", kwargs={
            "page_no": 1
        }))


class ExamCreateView(generic.CreateView):
    template_name = 'stdmanage/form.html'
    form_class = ExamForm
    model = Exam 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create Exam Record'
        context['submit_text'] = 'Create Exam'
        return context


class ExamUpdateView(generic.UpdateView):
    template_name = 'stdmanage/form.html'
    form_class = ExamForm
    model = Exam 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Exam Record'
        context['submit_text'] = 'Update Exam'
        return context


class ExamDeleteView(generic.DeleteView):
    model = Exam
    success_url = reverse_lazy('stdmanage:exam-list', kwargs={'page_no': 1})
    template_name = 'stdmanage/confirm_delete.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        the_object = self.model.objects.get(id = self.kwargs['pk'])
        title = "Are you sure you want to delete exam " + the_object.name + " ?" 
        context['title'] = title
        context['delete_url_name'] = 'stdmanage:exam-delete'
        context['go_back_url'] = reverse('stdmanage:exam-detail', kwargs={'pk': the_object.id})
        return context


class ExamDetailView(generic.DetailView):
    model = Exam


class ExamListView(StudentListView):
    template_name = 'stdmanage/exam_list.html'

    def get_list(self, request, *args, **kwargs):
        context = {}        
        exam_list = Exam.objects.all()

        return [context, exam_list]
    

stdmanage/templates/stdmanage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--Bootstrap-->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

  <style>
    body{
      font-family: "Open Sans",
      
    }
  </style>

  {% block additional_header %}{% endblock additional_header %}
  <title>{% block title %}Home | Student Management{% endblock title %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url "stdmanage:index"%}">Student Management</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{%url "stdmanage:student-create"%}">Add Students</a>
          <a class="nav-link" href="{%url "stdmanage:student-list" 1%}">Students List</a>
          <a class="nav-link" href="{%url "stdmanage:readingclass-list" 1%}">Manage Classes</a>
          <a class="nav-link" href="{%url "stdmanage:subject-list" 1%}">Manage Subjects</a>
          <a class="nav-link" href="{%url "stdmanage:exam-create"%}">Add Exams</a>
          <a class="nav-link" href="{%url "stdmanage:exam-list" 1%}">View Exams</a>
          <a class="nav-link" href="{%url "stdmanage:result-add-list" 1%}">Add Result</a>
          <a class="nav-link" href="{%url "stdmanage:result-list" 1%}">View Results</a>
          
        </div>
        
      </div>
    </div>
  </nav>


  {% block body %}

  {% endblock body %}
</body>
</html>

stdmanage/templates/stdmanage/exam_detail.html
{% extends 'stdmanage/base.html' %}
    
    {% block title %}{{object.name}}{% endblock title %}
    {% block body %}
    
      <div class="container">
        
        <div class="row">
            <div class="col-12 col-md-8 p-4 ">
                <h2 class="text-capitalize">{{object.name}}</h2>
                <div class="row">
                    <div class="col-4 col-md-3">
                        <span class="fw-bold">Exam Name: </span>
                    </div>
                    <div class="col-8 col-md-6">
                        {{object.name}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4 col-md-3">
                        <span class="fw-bold">Exam Description: </span>
                    </div>
                    <div class="col-8 col-md-6">
                        {{object.description}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4 col-md-3">
                        <span class="fw-bold">Exam Date: </span>
                    </div>
                    <div class="col-8 col-md-6">
                        {{object.date}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4 col-md-3">
                        <span class="fw-bold">Question Paper: </span>
                    </div>
                    <div class="col-8 col-md-6">
                        <a href="{{object.question_papers.url}}" download >
                            <button class="btn btn-secondary">Download</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8">
                <a href="{%url "stdmanage:exam-update" object.id%}"><button class="btn btn-secondary">Update</button></a>
                <a href="{%url "stdmanage:exam-delete" object.id%}"><button class="btn btn-danger">Delete</button></a>
            </div>
        </div>
      </div>

    {% endblock body %}

stdmanage/templates/stdmanage/index.html
{% extends 'stdmanage/base.html' %}

{% block body %}
<div class="container-fluid">
    <h4 class="p-3">Welcome to Dashboard of Student Management System</h4>
    <hr>
    <div class="row">
        <div class="col-md-4 col-12  p-3">
            <h4>Total Students: {{student_count}}</h4>  
            <a href="{%url "stdmanage:student-list" 1%}">See all students</a>
            <hr>
            <h5>Recently Added Students</h5>
            <hr>
            {% for i in recent_students %}
            <div class=" border-bottom my-2">
                <a href="{%url 'stdmanage:student-detail' i.id%}">{{i.full_name}}</a>
            </div>
            {% endfor %}
            <a href="{% url "stdmanage:student-create" %}">
                <button class= "btn btn-outline-dark my-2">
                    Add new Student <i class="bi bi-plus-square"></i>
                </button>
            </a>
        </div>
        <div class="col-12 col-md-8  p-3">
            <h4>Recent held exams</h4>
            <a href="{%url "stdmanage:exam-list" 1%}">See all exams</a>
            {% for i in recent_exams %}
            <h5>
                <a href="{%url "stdmanage:exam-detail" i.id%}">
                    {{i.name}}
                </a>
            </h5>
            {% endfor %}
            <a href="{%url "stdmanage:exam-create"%}">
                <button class="btn btn-outline-dark my-3 w-50">
                    <span>Held new Exam <i class="bi bi-book"></i></span>
                </button>
            </a>
        </div>
        <div class="col-12">
            <h4>
                Student Exam Performance
            </h4>
            <a href="{%url "stdmanage:result-list" 1%}">See Full Result list</a>
            <table class="table table-striped table-bordered">
                <thead class="table-dark">
                  <tr>
                    <th> Name </th>
                    <th> Class </th>
                    <th> Subject </th>
                    <th> Score </th>
                    <th> Anshwer Paper </th>
                    <th> Edit </th>
                    <th> Delete </th>
                  </tr>
                </thead>
                <tbody>
                  {% for result in recent_result %}
                    <tr>
                      <td> 
                          <a href="{%url 'stdmanage:student-detail' result.student.id%}">{{result.student.full_name}}</a> 
                      </td>
                      <td> {{result.student.reading_class}} </td>
                      <td> {{result.subject}} </td>
                      <td> {{result.score}} </td>
                      <td> <a target="blank" href="{{result.answer_sheet.url}}">Download</a> </td>
                      <td>
                          <a href="{%url "stdmanage:result-update" result.id%}">
                              <button class="btn btn-secondary">Update</button>
                          </a>
                      </td>
                      <td>
                          <a href="{%url "stdmanage:result-delete" result.id%}">
                              <button class="btn btn-danger">Delete</button>
                          </a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
          
              </table>
            
            <a href="{%url "stdmanage:result-add-list" 1%}">
                <button class="btn btn-outline-primary my-3 mx-auto d-block w-50">
                    <span>Add student performance <i class="bi bi-arrow-right-square"></i></span>
                </button>
            </a>
        </div>
    </div>
</div>
{% endblock body %}

stdmanage/templates/stdmanage/readingclass_list.html
{% extends 'stdmanage/base.html' %}
    
  {% block title %}All Classes{% endblock title %}
  {% block body %}
    
  <div class="container">
    
    <div class="row my-3">
      <div class="col-12 col-md-8">
        <h3>All Classes</h3> 
      </div>
    </div>
    
    <form action="{%url 'stdmanage:readingclass-list' 1%}" method="post">
      {% csrf_token %}
      <div class="row my-1">
        
        <div class="col-5 col-md-3">
          <select name="page_size" default='5' class="form-select" aria-label="Default select example">
            <option selected value = "{{page_size}}" >{{page_size}}</option>
            <option value="3">3</option>
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="30">30</option>
            <option value="50">50</option>
          </select>
        </div>

        <div class="col-2 col-md-2">
          <button class="btn btn-secondary">Set Params</button>
        </div>

      </div>
    </form> 
    
    <div class="row">
      <div class="col-md-8 col-sm-12">
        <table class="table table-striped table-bordered">
          <thead class="table-dark">
            <tr>
              <th> Reading Class ID </th>
              <th> Class Name </th>
              <th> Edit </th>
              <th> Delete </th>
            </tr>
          </thead>
          <tbody>
            {% for class in list_object %}
              <tr>
                <td> {{class.id}} </td>
                <td> {{class.name}} </td>
                <td>
                  <a href="{%url 'stdmanage:readingclass-update' class.id%}">
                      <button class="btn btn-secondary" >Edit</button>
                  </a>
                </td>
                <td>
                  <a href="{%url 'stdmanage:readingclass-delete' class.id%}">
                      <button class="btn btn-danger">Delete</button>
                  </a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    
    <div class="row">
      <div class="col">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="{%url 'stdmanage:readingclass-list' prev %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            
            {% for i in pages %}
              {% if i == current %}
                <li class="page-item"><a class="page-link active" href="{%url 'stdmanage:readingclass-list' i %}">
              {% else %}
                <li class="page-item"><a class="page-link" href="{%url 'stdmanage:readingclass-list' i %}">   
              {% endif %}
            {{i}}
            </a></li>
            {% endfor %}
            
            <li class="page-item">
              <a class="page-link" href="{%url 'stdmanage:readingclass-list' next %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </div>

    <a href="{%url "stdmanage:readingclass-create"%}">
      <button class="btn btn-outline-primary my-3">
          <span>Create new class <i class="bi bi-arrow-right-square"></i></span>
      </button>
    </a>
  
  </div>

  {% endblock body %}

stdmanage/templates/stdmanage/result_form.html
{% extends 'stdmanage/base.html' %}
    
    {% block title %} Add Result {% endblock title %}
    {% block body %}
    
    {%load crispy_forms_tags%}

      <div class="container">
        <h3>Add Result</h3>
        
        <div class="row">
          <div class="col-12 col-md-6">
            <form action="{%url 'stdmanage:result-create-basic'%}" method="post" enctype="multipart/form-data">
              {%csrf_token%}
              {{form|crispy}}
              <div class="row my-3">
                <div class="col">
                  <button type="submit" class="btn btn-dark">Add Entry</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>

    {% endblock body %}
    

stdmanage/templates/stdmanage/student_detail.html
{% extends 'stdmanage/base.html' %}
    
    {% block title %}Student List{% endblock title %}
    {% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8 p-4 ">
                <h2 class="text-capitalize">{{student_detail.full_name}}</h2>
                <div class="row">
                    <div class="col-4 col-md-3">
                        <span class="fw-bold">Class: </span>
                    </div>
                    <div class="col-8 col-md-6">
                        {{student_detail.reading_class}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4 col-md-3">
                        <span class="fw-bold">Date of birth: </span>
                    </div>
                    <div class="col-8 col-md-6">
                        {{student_detail.date_of_birth}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4 col-md-3">
                        <span class="fw-bold">Phone: </span>
                    </div>
                    <div class="col-8 col-md-6">
                        {{student_detail.phone_number}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4 col-md-3">
                        <span class="fw-bold">Address: </span>
                    </div>
                    <div class="col-8 col-md-6">
                        {{student_detail.home_address}}
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-4 p-4 ">
                <img src="{{ student_detail.photo.url }}" class="img-fluid img-thumbnail" srcset="">
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8">
                <a href="{%url "stdmanage:student-update" student_detail.id%}"><button class="btn btn-secondary">Update</button></a>
                <a href="{%url "stdmanage:student-delete" student_detail.id%}"><button class="btn btn-danger">Delete</button></a>
            </div>
        </div>
    </div>
    {% endblock body %}